# Generated by Django 5.0 on 2023-12-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
