# Generated by Django 5.0 on 2023-12-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPIs', '0003_alter_product_data_available_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='available_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
